apiVersion: v1
kind: Service
metadata:
  name: {{ include "tee-prover-server.fullname" . }}
  labels:
    {{- include "tee-prover-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    {{- include "tee-prover-server.selectorLabels" . | nindent 4 }}
