
#  inputs from { sigAlg: 'rsa', hashFunction: 'sha256'}

dg1 = [
    "97",
    "91",
    "95",
    "31",
    "88",
    "80",
    "60",
    "70",
    "82",
    "65",
    "68",
    "85",
    "80",
    "79",
    "78",
    "84",
    "60",
    "60",
    "65",
    "76",
    "80",
    "72",
    "79",
    "78",
    "83",
    "69",
    "60",
    "72",
    "85",
    "71",
    "72",
    "85",
    "69",
    "83",
    "60",
    "65",
    "76",
    "66",
    "69",
    "82",
    "84",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "49",
    "53",
    "65",
    "65",
    "56",
    "49",
    "50",
    "51",
    "52",
    "52",
    "70",
    "82",
    "65",
    "48",
    "48",
    "48",
    "49",
    "48",
    "49",
    "49",
    "77",
    "51",
    "48",
    "48",
    "49",
    "48",
    "49",
    "53",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "60",
    "48",
    "50"
  ]
dg1_hash_offset = "37"
dg2_hash = [
    "190",
    "82",
    "180",
    "235",
    "222",
    "33",
    "79",
    "50",
    "152",
    "136",
    "142",
    "35",
    "116",
    "224",
    "6",
    "242",
    "156",
    "141",
    "128",
    "248",
    "10",
    "61",
    "98",
    "86",
    "248",
    "45",
    "207",
    "210",
    "90",
    "232",
    "175",
    "38",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ]
eContent = [
    "224",
    "160",
    "251",
    "32",
    "217",
    "3",
    "37",
    "146",
    "50",
    "222",
    "84",
    "2",
    "10",
    "77",
    "79",
    "174",
    "55",
    "40",
    "132",
    "139",
    "206",
    "77",
    "40",
    "116",
    "244",
    "59",
    "49",
    "73",
    "132",
    "133",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "155",
    "69",
    "163",
    "24",
    "248",
    "167",
    "161",
    "54",
    "179",
    "18",
    "174",
    "196",
    "232",
    "60",
    "51",
    "198",
    "140",
    "219",
    "196",
    "229",
    "145",
    "248",
    "154",
    "203",
    "178",
    "114",
    "17",
    "33",
    "54",
    "80",
    "127",
    "173",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "190",
    "82",
    "180",
    "235",
    "222",
    "33",
    "79",
    "50",
    "152",
    "136",
    "142",
    "35",
    "116",
    "224",
    "6",
    "242",
    "156",
    "141",
    "128",
    "248",
    "10",
    "61",
    "98",
    "86",
    "248",
    "45",
    "207",
    "210",
    "90",
    "232",
    "175",
    "38",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "194",
    "104",
    "108",
    "237",
    "246",
    "97",
    "230",
    "116",
    "198",
    "69",
    "110",
    "26",
    "87",
    "17",
    "89",
    "110",
    "199",
    "108",
    "250",
    "36",
    "21",
    "39",
    "87",
    "110",
    "102",
    "250",
    "213",
    "174",
    "131",
    "171",
    "174",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "136",
    "155",
    "87",
    "144",
    "111",
    "15",
    "152",
    "127",
    "85",
    "25",
    "154",
    "81",
    "20",
    "58",
    "51",
    "75",
    "193",
    "116",
    "234",
    "0",
    "60",
    "30",
    "29",
    "30",
    "183",
    "141",
    "72",
    "247",
    "255",
    "203",
    "100",
    "124",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "41",
    "234",
    "106",
    "78",
    "31",
    "11",
    "114",
    "137",
    "237",
    "17",
    "92",
    "71",
    "134",
    "47",
    "62",
    "78",
    "189",
    "233",
    "201",
    "214",
    "53",
    "4",
    "47",
    "189",
    "201",
    "133",
    "6",
    "121",
    "34",
    "131",
    "64",
    "142",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "91",
    "222",
    "210",
    "193",
    "62",
    "222",
    "104",
    "82",
    "36",
    "41",
    "138",
    "253",
    "70",
    "15",
    "148",
    "208",
    "156",
    "45",
    "105",
    "171",
    "241",
    "195",
    "185",
    "43",
    "217",
    "162",
    "146",
    "201",
    "222",
    "89",
    "238",
    "38",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "76",
    "123",
    "216",
    "13",
    "51",
    "227",
    "72",
    "245",
    "59",
    "193",
    "238",
    "166",
    "103",
    "49",
    "23",
    "164",
    "171",
    "188",
    "194",
    "197",
    "156",
    "187",
    "249",
    "28",
    "198",
    "95",
    "69",
    "15",
    "182",
    "56",
    "54",
    "38",
    "128",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "9",
    "120",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
]
signed_attr =  [
    "49",
    "102",
    "48",
    "21",
    "6",
    "9",
    "42",
    "134",
    "72",
    "134",
    "247",
    "13",
    "1",
    "9",
    "3",
    "49",
    "8",
    "6",
    "6",
    "103",
    "129",
    "8",
    "1",
    "1",
    "1",
    "48",
    "28",
    "6",
    "9",
    "42",
    "134",
    "72",
    "134",
    "247",
    "13",
    "1",
    "9",
    "5",
    "49",
    "15",
    "23",
    "13",
    "49",
    "57",
    "49",
    "50",
    "49",
    "54",
    "49",
    "55",
    "50",
    "50",
    "51",
    "56",
    "90",
    "48",
    "47",
    "6",
    "9",
    "42",
    "134",
    "72",
    "134",
    "247",
    "13",
    "1",
    "9",
    "4",
    "49",
    "34",
    "4",
    "32",
    "177",
    "155",
    "49",
    "181",
    "14",
    "247",
    "85",
    "87",
    "152",
    "110",
    "27",
    "53",
    "143",
    "167",
    "42",
    "52",
    "212",
    "157",
    "229",
    "85",
    "250",
    "130",
    "71",
    "58",
    "47",
    "23",
    "4",
    "237",
    "154",
    "139",
    "205",
    "116",
    "128",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "3",
    "64",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ]
signed_attr_econtent_hash_offset = "72"
eContent_padded_length = "320"
signed_attr_padded_length = "128"
