name: Deploy workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

permissions:
  contents: read
  id-token: write

jobs:
  prod:
    uses: ./.github/workflows/artifacts.yml
    secrets: inherit
    if: github.ref == 'refs/heads/main'
    with:
      environment: "PRD"
      tag: "latest"

  stg:
    uses: ./.github/workflows/artifacts.yml
    secrets: inherit
    if: github.ref == 'refs/heads/staging'
    with:
      environment: "STG"
      tag: "stg"
