name: Deploy workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stg

jobs:
  prod:
    uses: ./.github/workflows/artifacts.yml
    secrets: inherit
    if: github.ref == 'refs/heads/main'
    with:
      runner: "prod-runner"
      environment: "PRD"
      tag: "latest"

  stg:
    uses: ./.github/workflows/artifacts.yml
    secrets: inherit
    if: github.ref == 'refs/heads/staging'
    with:
      runner: "stg-runner"
      environment: "STG"
      tag: "stg"
