name: Deploy TEE images
on:
  workflow_call:
    inputs:
      environment:
        description: The GitHub Actions environment
        required: true
        type: string
      proofType:
        description: The proof type
        required: true
        type: string
      size:
        description: The size
        required: true
        type: string
      tag:
        description: The tag
        required: true
        type: string
      
jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Artifacts
        run: |
          ARTIFACT_URL=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/selfxyz/self/actions/artifacts" \
            | jq '.artifacts | max_by(.created_at)' | jq -r .'archive_download_url')
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV

      - name: Download and unpack artifact
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -o artifact.zip \
            "$ARTIFACT_URL"

      - name: Sort circuits
        run: | 
          unzip artifact.zip -d ./circuits/
          chmod +x sort_circuits.sh
          ./sort_circuits.sh

      - name: Login to AWS
        run: |
          aws --profile default configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws --profile default configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Download and unpack zkeys
        run: |
          rm -rf zkeys
          chmod +x download_zkeys.sh && ./download_zkeys.sh
          mkdir zkeys
          for file in *_final.zkey; do mv "$file" "zkeys/${file%_final.zkey}.zkey"; done

      - name: Reformat zkeys
        run: |
          mkdir -p zkeys/register zkeys/disclose zkeys/dsc
          mv zkeys/register_* zkeys/register/
          mv zkeys/vc_and_disclose.zkey zkeys/disclose/ 
          mv zkeys/dsc_* zkeys/dsc/
          chmod +x sort_zkeys.sh
          ./sort_zkeys.sh

      - name: Init submodules
        run: |
          git submodule update --init
          cd rapidsnark && git submodule update --init && cd ..

      - name: Login to Docker Hub
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker enclave images
        if: inputs.proofType == 'all'
        run: |
          chmod +x ./build_docker_images.sh
          ./build_docker_images.sh ${{ secrets.DOCKER_ORGANIZATION }} ${{ inputs.tag }} nitro-enclave
      
      - name: Build and push Docker enclave image
        if: inputs.proofType != 'all'
        run: |
          chmod +x ./build_docker.sh
          ./build_docker.sh ${{ secrets.DOCKER_ORGANIZATION }} ${{ inputs.proofType }} ${{ inputs.size }} ${{ inputs.tag }}

      - name: Cleanup zkeys
        run: rm -rf zkeys*

      - name: Push images
        run: |
          chmod +x push_docker.sh
          ./push_docker.sh ${{ secrets.DOCKER_ORGANIZATION }} ${{ inputs.tag }}